
models:
  - name: dim_date
    description: "Dimensión de tiempo. Granularidad: un día. Rango 1992–1998."
    columns:
      - name: date_key
        description: "Surrogate key en formato YYYYMMDD"
        data_tests:
          - not_null
          - unique
      - name: full_date
        data_tests:
          - not_null
          - unique
      - name: day_of_week
        data_tests:
          - not_null
          - accepted_values:
              arguments:
                values: [0, 1, 2, 3, 4, 5, 6]
      - name: is_weekend
        data_tests:
          - not_null
          - accepted_values:
              arguments:
                values: [true, false]

  - name: fct_lineitem
    description: "Tabla de hechos principal. Granularidad: una fila por línea de pedido."
    columns:
      - name: order_key
        data_tests:
          - not_null
      - name: date_key
        data_tests:
          - not_null
          #relationships: {to: ref('dim_date'), field: date_key}]
      - name: customer_key
        data_tests: 
          - not_null
          #relationships: {to: ref('dim_customer'), field: customer_key}]
      - name: net_amount
        data_tests: 
          - not_null

  - name: dim_customer
    columns:
      - name: customer_key
        data_tests:
          - not_null
          - unique
      - name: market_segment
        data_tests:
            - not_null

  - name: dim_part
    columns:
      - name: part_key
        data_tests:
          - not_null
          - unique
      - name: part_name
        data_tests:
            - not_null